-- ==========================================================
-- FocusFeed: Schema de Base de Datos para Supabase (PostgreSQL)
-- ==========================================================

-- 1. Tabla de Canales y Fuentes (Feeds)
CREATE TABLE IF NOT EXISTS public.feeds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    feed_url TEXT UNIQUE NOT NULL,
    site_url TEXT,
    feed_type TEXT NOT NULL DEFAULT 'youtube', -- 'youtube', 'rss', 'substack', 'podcast'
    channel_id TEXT,
    custom_category TEXT DEFAULT 'General',
    icon_url TEXT,
    is_active BOOLEAN DEFAULT true,
    last_synced_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla de Items / Videos / Artículos
CREATE TABLE IF NOT EXISTS public.items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_id BIGINT REFERENCES public.feeds(id) ON DELETE CASCADE,
    guid TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    author TEXT,
    published_at TIMESTAMPTZ,
    content_type TEXT NOT NULL DEFAULT 'video', -- 'video', 'article', 'audio'
    video_id TEXT,
    thumbnail_url TEXT,
    duration_seconds INTEGER DEFAULT 0,
    raw_content TEXT,
    transcript TEXT,
    
    -- Enriquecimiento de IA
    relevance_score INTEGER DEFAULT 0, -- 0 a 100
    summary_tldr TEXT,
    key_takeaways TEXT,
    curator_note TEXT,
    topic_tags TEXT,
    ai_processed INTEGER DEFAULT 0,
    ai_processed_at TIMESTAMPTZ,
    
    -- Estado y Aprendizaje Adaptativo (RLHF)
    status TEXT DEFAULT 'inbox', -- 'inbox', 'reading', 'archived'
    user_rating TEXT DEFAULT 'none', -- 'love', 'like', 'dislike', 'none'
    user_feedback_comment TEXT,
    feedback_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabla de Perfil y Aprendizaje de Preferencias
CREATE TABLE IF NOT EXISTS public.user_profile (
    id BIGINT PRIMARY KEY DEFAULT 1,
    user_name TEXT DEFAULT 'León Velázquez',
    focus_topics TEXT,
    system_prompt_criteria TEXT,
    learned_preferences TEXT,
    min_relevance_threshold INTEGER DEFAULT 60,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insertar perfil por defecto si no existe
INSERT INTO public.user_profile (id, user_name, focus_topics, system_prompt_criteria, learned_preferences)
VALUES (
    1,
    'León Velázquez',
    '["Inteligencia Artificial Aplicada y Sistemas Agénticos", "Gestión del Conocimiento Personal (PKM, Obsidian, Zettelkasten)", "Transformación Institucional y Modelos Educativos (MAPS, FIT)", "Cine de autor, narrativa visual y formato gran escala", "Música contemporánea, post-punk, vinilos y análisis cultural", "Enología y exploración gastronómica"]',
    'Prioriza profundidad conceptual, rigor analítico y valor duradero. Descarta clickbait y noticias superficiales.',
    '{"boosted_authors": [], "boosted_tags": {}, "penalized_tags": {}}'
)
ON CONFLICT (id) DO NOTHING;

-- Habilitar acceso de lectura y escritura para API anónima / service role
ALTER TABLE public.feeds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profile ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir todo acceso público/autenticado a feeds" ON public.feeds FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo acceso público/autenticado a items" ON public.items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo acceso público/autenticado a user_profile" ON public.user_profile FOR ALL USING (true) WITH CHECK (true);
