-- ==========================================================
-- FocusFeed v2: corpus compartido + estado por usuario
-- ==========================================================
--
-- QUÉ CAMBIA CONTRA v1
--   items    → deja de tener estado personal. Es corpus global.
--              El resumen de un artículo se calcula UNA vez y sirve para todos.
--   feeds    → global, sin dueño. La categoría pasa a ser preferencia del usuario.
--   NUEVO subscriptions → quién sigue qué feed.
--   NUEVO user_items    → estado personal: visto, guardado, score, rating.
--   NUEVO ai_usage      → tokens y costo por usuario. Sin esto no hay precio.
--   user_profile → una fila por usuario, no la fila id=1.
--
-- CÓMO CORRERLO
--   1. Sustituye :OWNER_ID por el uuid de tu cuenta de Supabase Auth.
--      Si aún no existe, usa '00000000-0000-0000-0000-000000000001' y
--      corre después el UPDATE del bloque de migración.
--   2. Ejecuta este archivo completo en el SQL editor de Supabase.
--   3. Verifica con las consultas del bloque final.
--
-- ROLLBACK
--   Las tablas de v1 no se borran. Si algo sale mal:
--     DROP TABLE user_items, subscriptions, ai_usage;
--     ALTER TABLE items RENAME COLUMN ... (ver bloque 6)
--   Los datos originales siguen en items_v1_backup.
-- ==========================================================

BEGIN;

-- ----------------------------------------------------------
-- 0. Respaldo antes de tocar nada
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.items_v1_backup AS SELECT * FROM public.items;
CREATE TABLE IF NOT EXISTS public.feeds_v1_backup AS SELECT * FROM public.feeds;
CREATE TABLE IF NOT EXISTS public.user_profile_v1_backup AS SELECT * FROM public.user_profile;

-- ----------------------------------------------------------
-- 1. subscriptions: quién sigue qué
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    feed_id BIGINT NOT NULL REFERENCES public.feeds(id) ON DELETE CASCADE,
    custom_category TEXT DEFAULT 'General',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_id, feed_id)
);
CREATE INDEX IF NOT EXISTS idx_subs_user ON public.subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_subs_feed ON public.subscriptions(feed_id);

-- ----------------------------------------------------------
-- 2. user_items: estado personal sobre el corpus global
--    La fila solo existe cuando hubo interacción o score.
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    item_id BIGINT NOT NULL REFERENCES public.items(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'inbox',
    relevance_score INTEGER,
    curator_note TEXT,
    user_rating TEXT DEFAULT 'none',
    user_feedback_comment TEXT,
    feedback_at TIMESTAMPTZ,
    scored_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_id, item_id)
);
CREATE INDEX IF NOT EXISTS idx_uitems_user_status ON public.user_items(user_id, status);
CREATE INDEX IF NOT EXISTS idx_uitems_item ON public.user_items(item_id);

-- ----------------------------------------------------------
-- 3. ai_usage: la factura. Sin esto no se puede poner precio.
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ai_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    item_id BIGINT,
    kind TEXT NOT NULL DEFAULT 'item_analysis',
    model TEXT,
    input_tokens INTEGER DEFAULT 0,
    output_tokens INTEGER DEFAULT 0,
    cost_usd NUMERIC(10,6) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_usage_user_date ON public.ai_usage(user_id, created_at);

-- ----------------------------------------------------------
-- 4. user_profile por usuario
-- ----------------------------------------------------------
ALTER TABLE public.user_profile ADD COLUMN IF NOT EXISTS user_id UUID;
ALTER TABLE public.user_profile ADD COLUMN IF NOT EXISTS plan TEXT DEFAULT 'free';
ALTER TABLE public.user_profile ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

UPDATE public.user_profile
   SET user_id = '00000000-0000-0000-0000-000000000001'::uuid
 WHERE user_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_profile_user ON public.user_profile(user_id);

-- ----------------------------------------------------------
-- 5. Migrar el estado personal de items a user_items
--    Solo se migran los items que tienen estado real.
-- ----------------------------------------------------------
INSERT INTO public.user_items (user_id, item_id, status, relevance_score, curator_note,
                               user_rating, user_feedback_comment, feedback_at)
SELECT '00000000-0000-0000-0000-000000000001'::uuid,
       i.id,
       COALESCE(i.status, 'inbox'),
       i.relevance_score,
       i.curator_note,
       COALESCE(i.user_rating, 'none'),
       i.user_feedback_comment,
       i.feedback_at
  FROM public.items i
 WHERE COALESCE(i.status, 'inbox') <> 'inbox'
    OR COALESCE(i.user_rating, 'none') <> 'none'
    OR i.relevance_score IS NOT NULL
ON CONFLICT (user_id, item_id) DO NOTHING;

-- Migrar las suscripciones: todos los feeds actuales son del dueño
INSERT INTO public.subscriptions (user_id, feed_id, custom_category)
SELECT '00000000-0000-0000-0000-000000000001'::uuid, f.id, COALESCE(f.custom_category, 'General')
  FROM public.feeds f
ON CONFLICT (user_id, feed_id) DO NOTHING;

-- ----------------------------------------------------------
-- 6. items queda como corpus global
--    Las columnas personales se renombran en lugar de borrarse,
--    para poder revertir. Se eliminan en una migración posterior.
-- ----------------------------------------------------------
ALTER TABLE public.items RENAME COLUMN status TO legacy_status;
ALTER TABLE public.items RENAME COLUMN user_rating TO legacy_user_rating;
ALTER TABLE public.items RENAME COLUMN user_feedback_comment TO legacy_feedback_comment;
ALTER TABLE public.items RENAME COLUMN feedback_at TO legacy_feedback_at;
ALTER TABLE public.items RENAME COLUMN relevance_score TO legacy_relevance_score;
ALTER TABLE public.items RENAME COLUMN curator_note TO legacy_curator_note;

-- ----------------------------------------------------------
-- 7. Lecturas del feed vía RPC
--    Une corpus global con estado personal en una sola llamada.
-- ----------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_user_feed(
    p_user_id UUID,
    p_tab TEXT DEFAULT 'curated',
    p_type TEXT DEFAULT 'all',
    p_limit INTEGER DEFAULT 120
)
RETURNS TABLE (
    id BIGINT, feed_id BIGINT, guid TEXT, title TEXT, url TEXT, author TEXT,
    published_at TIMESTAMPTZ, content_type TEXT, video_id TEXT, thumbnail_url TEXT,
    raw_content TEXT, summary_tldr TEXT, key_takeaways TEXT, topic_tags TEXT,
    ai_processed INTEGER,
    status TEXT, relevance_score INTEGER, curator_note TEXT, user_rating TEXT,
    user_feedback_comment TEXT
)
LANGUAGE sql STABLE AS $$
    SELECT i.id, i.feed_id, i.guid, i.title, i.url, i.author,
           i.published_at, i.content_type, i.video_id, i.thumbnail_url,
           i.raw_content, i.summary_tldr, i.key_takeaways, i.topic_tags,
           i.ai_processed,
           COALESCE(ui.status, 'inbox')      AS status,
           ui.relevance_score,
           ui.curator_note,
           COALESCE(ui.user_rating, 'none')  AS user_rating,
           ui.user_feedback_comment
      FROM public.items i
      JOIN public.subscriptions s
        ON s.feed_id = i.feed_id AND s.user_id = p_user_id
      LEFT JOIN public.user_items ui
        ON ui.item_id = i.id AND ui.user_id = p_user_id
     WHERE (p_type = 'all' OR i.content_type = p_type)
       AND (
            (p_tab = 'curated'  AND COALESCE(ui.status,'inbox') <> 'archived')
         OR (p_tab = 'inbox'    AND COALESCE(ui.status,'inbox') = 'inbox')
         OR (p_tab = 'reading'  AND ui.status = 'reading')
         OR (p_tab = 'archived' AND ui.status = 'archived')
       )
     ORDER BY
        CASE WHEN p_tab = 'curated' THEN COALESCE(ui.relevance_score, 70) END DESC NULLS LAST,
        i.published_at DESC
     LIMIT p_limit;
$$;

CREATE OR REPLACE FUNCTION public.get_user_counts(p_user_id UUID)
RETURNS TABLE (status TEXT, cnt BIGINT)
LANGUAGE sql STABLE AS $$
    SELECT COALESCE(ui.status, 'inbox') AS status, COUNT(*)::BIGINT
      FROM public.items i
      JOIN public.subscriptions s
        ON s.feed_id = i.feed_id AND s.user_id = p_user_id
      LEFT JOIN public.user_items ui
        ON ui.item_id = i.id AND ui.user_id = p_user_id
     GROUP BY 1;
$$;

-- Items del corpus que nadie ha analizado todavía.
-- El resumen es universal, así que se calcula una vez para todos.
CREATE OR REPLACE FUNCTION public.get_unanalyzed_items(p_limit INTEGER DEFAULT 10)
RETURNS TABLE (id BIGINT)
LANGUAGE sql STABLE AS $$
    SELECT i.id FROM public.items i
     WHERE COALESCE(i.ai_processed, 0) = 0
     ORDER BY i.published_at DESC
     LIMIT p_limit;
$$;

-- ----------------------------------------------------------
-- 8. RLS. Cada quien ve lo suyo; el corpus es de lectura común.
-- ----------------------------------------------------------
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_items    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_usage      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profile  ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS own_subscriptions ON public.subscriptions;
CREATE POLICY own_subscriptions ON public.subscriptions
    USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS own_user_items ON public.user_items;
CREATE POLICY own_user_items ON public.user_items
    USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS own_usage ON public.ai_usage;
CREATE POLICY own_usage ON public.ai_usage
    FOR SELECT USING (user_id = auth.uid());

DROP POLICY IF EXISTS own_profile ON public.user_profile;
CREATE POLICY own_profile ON public.user_profile
    USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

-- Corpus global: lectura para cualquier sesión autenticada, escritura solo del servidor
ALTER TABLE public.feeds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS read_feeds ON public.feeds;
CREATE POLICY read_feeds ON public.feeds FOR SELECT USING (true);

DROP POLICY IF EXISTS read_items ON public.items;
CREATE POLICY read_items ON public.items FOR SELECT USING (true);

-- El backend escribe con service_role, que pasa por encima de RLS.
REVOKE ALL ON public.feeds FROM anon;
REVOKE ALL ON public.items FROM anon;
GRANT SELECT ON public.feeds TO authenticated;
GRANT SELECT ON public.items TO authenticated;
GRANT ALL ON public.subscriptions, public.user_items, public.user_profile TO authenticated;
GRANT SELECT ON public.ai_usage TO authenticated;

COMMIT;

-- ==========================================================
-- Verificación después de correr
-- ==========================================================
-- SELECT COUNT(*) FROM subscriptions;   -- debe igualar el número de feeds
-- SELECT COUNT(*) FROM user_items;      -- items con estado real migrados
-- SELECT * FROM get_user_feed('00000000-0000-0000-0000-000000000001'::uuid,'curated','all',5);
-- SELECT * FROM get_user_counts('00000000-0000-0000-0000-000000000001'::uuid);
